### ISSUE TITLE
fail to run the project

### ISSUE THREAD

**Issue by LiogiShiki** [Hanlin-Zhou/OpenGL-VXGI-Engine#1]
i am trying this project in windows, cmake generation and code complie in VS2022 work fine,but the program fail to run.Should I use debug\release mode or simply run the .exe?

**Comment by Hanlin-Zhou** [comment]
Rebuild the glfw in the source folder. You can follow the instructions on learnopengl website.

**Comment by mmmovania** [comment]
The project even though compiles and runs but misses the following shaders therefore you will no get any useful output.
```
VoxelVisFace.vert
VoxelVisFace.frag
VoxelVisTrace.vert
VoxelVisTrace.frag
```
I scanned through the repo and I feel the shader files are removed on purpose by the author since these are given in the .gitignore file hence they wont be uploaded to the github repo. This sort of kills the purpose of making the code since the results cant be reproduced.

**Comment by Hanlin-Zhou** [comment]
> The project even though compiles and runs but misses the following shaders therefore you will no get any useful output.
> 
> ```
> VoxelVisFace.vert
> VoxelVisFace.frag
> VoxelVisTrace.vert
> VoxelVisTrace.frag
> ```
> 
> I scanned through the repo and I feel the shader files are removed on purpose by the author since these are given in the .gitignore file hence they wont be uploaded to the github repo. This sort of kills the purpose of making the code since the results cant be reproduced.

These are the old debug shader files that dont work anymore. The issue was with cmake and GLFW source code. I have replaced the glfw source code with glfw binaries. Now it should run after building with cmake.
